use_frameworks!

target 'FoodFactsSDK_Example' do
 pod 'SwiftyJSON', '2.4.0'
 pod 'Alamofire', '~> 3.5'
  pod 'FoodFactsSDK', :path => '../'

  target 'FoodFactsSDK_Tests' do
    inherit! :search_paths

    
  end
end
