use_frameworks!

target 'FoodFactsSDK_Example' do
    pod 'FoodFactsSDK', :path => '../'
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.3'

  target 'FoodFactsSDK_Tests' do
    inherit! :search_paths

    
  end
end
